name: Stale
on:
  schedule: [{ cron: "0 13 * * 1-5" }]
permissions:
  pull-requests: write
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 45
          days-before-close: 10
          stale-issue-label: "🧽 Invalid"
          exempt-issue-labels: "🟣 Good First Issue,🧱 Blocked"
          remove-stale-when-updated: true